import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { ReactQueryClient } from "./ReactQueryClient";
import StyledComponentsRegistry from "./providers";
import { Footer } from "./Components/Footer";
import { Navbar } from "./Components/Navbar";

const getSchwifty = localFont({
  src: "./assets/get_schwifty.ttf",
});

export const metadata: Metadata = {
  title: "Rick and Morty Curious",
  description: "Generated by Luis Renato Toniati",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <ReactQueryClient>
        <StyledComponentsRegistry>
          <body className={getSchwifty.className}>
            <Navbar />

            {children}
            <Footer />
          </body>
        </StyledComponentsRegistry>
      </ReactQueryClient>
    </html>
  );
}
